### PR TITLE
Fix the spark/hdfs builds by cleaning up /etc/hosts and adding spark_local_ip to spark_env.sh

### LINKED ISSUE #151: Github action sporadic failure with spark
Some [builds](https://github.com/GenomicsDB/GenomicsDB/actions/runs/731278279) fail with `sparkDriver` not able to find a random free port. Most of the time, restarting the build works. But just wondering if you can take a look.

```
2021-04-11T18:38:04.1426794Z Sanity test with query.json : spark-submit --master local --deploy-mode client --total-executor-cores 1 --executor-memory 512M  --conf "spark.executor.extraJavaOptions=" --conf "spark.driver.extraJavaOptions=" --class org.genomicsdb.spark.api.GenomicsDBSparkBindings /home/runner/work/GenomicsDB/GenomicsDB/build/target/genomicsdb-x.y.z.test-allinone.jar /tmp/tmp69y8hzf7/sanity_test/t0_1_2.json /tmp/tmp69y8hzf7/sanity_test/query.json failed
2021-04-11T18:38:04.1429971Z Stdout:
2021-04-11T18:38:04.1431279Z Stderr: 21/04/11 18:38:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-04-11T18:38:04.1432436Z 21/04/11 18:38:03 INFO SparkContext: Running Spark version 3.0.1
2021-04-11T18:38:04.1433443Z 21/04/11 18:38:03 INFO ResourceUtils: ==============================================================
2021-04-11T18:38:04.1437692Z 21/04/11 18:38:03 INFO ResourceUtils: Resources for spark.driver:
2021-04-11T18:38:04.1438166Z
2021-04-11T18:38:04.1438643Z 21/04/11 18:38:03 INFO ResourceUtils: ==============================================================
2021-04-11T18:38:04.1439513Z 21/04/11 18:38:03 INFO SparkContext: Submitted application: GenomicsDB API Experimental Bindings
2021-04-11T18:38:04.1440442Z 21/04/11 18:38:03 INFO SecurityManager: Changing view acls to: runner
2021-04-11T18:38:04.1441398Z 21/04/11 18:38:03 INFO SecurityManager: Changing modify acls to: runner
2021-04-11T18:38:04.1442177Z 21/04/11 18:38:03 INFO SecurityManager: Changing view acls groups to:
2021-04-11T18:38:04.1442970Z 21/04/11 18:38:03 INFO SecurityManager: Changing modify acls groups to:
2021-04-11T18:38:04.1444518Z 21/04/11 18:38:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(runner); groups with view permissions: Set(); users  with modify permissions: Set(runner); groups with modify permissions: Set()
2021-04-11T18:38:04.1446748Z 21/04/11 18:38:04 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
...
2021-04-11T18:38:04.1456342Z 21/04/11 18:38:04 WARN Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.
2021-04-11T18:38:04.1472401Z java.net.BindException: Cannot assign requested address: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address.
2021-04-11T18:38:04.1475406Z  at sun.nio.ch.Net.bind0(Native Method)
2021-04-11T18:38:04.1476149Z  at sun.nio.ch.Net.bind(Net.java:461)
2021-04-11T18:38:04.1476956Z  at sun.nio.ch.Net.bind(Net.java:453)
...
```

### PR DESCRIPTION
**Pull request by nalinigans**
Fix #151 by cleaning up /etc/hosts and adding spark_local_ip directly to spark_env.sh.

### CODE REVIEW

**Comment by nalinigans** [comment]
@mlathara, see this https://github.com/apache/spark/pull/24559#issuecomment-814507882 where spark Github Action builds are facing the same port binding issue.

**Comment by nalinigans** [comment]
Filed https://github.community/t/builds-with-spark-failing-with-java-net-bindexception-with-spark-commands/175470

**Comment by nalinigans** [comment]
@jacmarjorie, @mlathara, still can't run spark 2 builds successfully, although spark 3 now is fine. If you are OK, lets pull this in to allow for other PRs and functionality as spark 3 at least gets tested. If one of you have ideas, please let me know. As you can see from the results of `lsof`, the ports 4000-4016 are not in use at all.

**Review by mlathara — APPROVED** [review]
looks good to me, and i'm okay with ignoring the spark2 failures for now...

**Comment by nalinigans** [comment]
Fixed the `spark 2` issue by assigning both spark master and local ip to 127.0.0.1 in spark_env.sh. Also, got tripped with caching of spark as that missed the configuration fix, have bumped up the cache version for now.

**Review by mlathara — APPROVED** [review]
nice job!

**Pull request merged**
