### PR TITLE
Support building and testing of GenomicsDB on ubuntu 22.04

### PR DESCRIPTION
**Pull request by nalinigans**
To support Github Actions on `ubuntu 22.04` and for general building and testing on `ubuntu 22.04` -

- Install openssl 1.1 explicitly for Ubuntu 22.04 in Github workflows. This will be changed once https://github.com/OmicsDataAutomation/TileDB/pull/143 is complete
- Explicitly configure htslib `--without-libdeflate` option as it picks it up when it is installed
- Remove MPI support for JNI as it is leading to segfaults during shutdown and we don't use MPI from Java currently
- Some scripts cleanup.

### CODE REVIEW

**Comment by nalinigans** [comment]
@eneskuluk, let us know what you find when you run on your ubuntu 22.04 laptop with vscode. Thanks.

**Comment by eneskuluk** [comment]
I tested the branch on WSL 22.04 with following instructions:

- Removed the current GenomicsDb folder and cloned from git again, checkout to this branch.
- Used following cmake command:  cmake -DCMAKE_INSTALL_PREFIX=$HOME  -DCMAKE_BUILD_TYPE=Debug -DBUILD_JAVA=1 ..
- After that I executed make, make install and make test one by one.
- On make test it passed all tests except CI tests due to it didn't find python executable. This was expected and related to the installation on my end.
- Ran run.py to manually execute CI_tests with following command: python3 run.py ../build $HOME and it passed.
It did build, compile and passed the test on my end.

**Comment by nalinigans** [comment]
> @nalinigans I tested the branch on WSL 22.04 with following instructions:
> 
> * Removed the current GenomicsDb folder and cloned from git again, checkout to this branch.
> * Used following cmake command:  cmake -DCMAKE_INSTALL_PREFIX=$HOME  -DCMAKE_BUILD_TYPE=Debug -DBUILD_JAVA=1 ..
> * After that I executed make, make install and make test one by one.
> * On make test it passed all tests except CI tests due to it didn't find python executable. This was expected and related to the installation on my end.
> * Ran run.py to manually execute CI_tests with following command: python3 run.py ../build $HOME and it passed.
>   It did build, compile and passed the tests on my end.

Thanks @eneskuluk. I have updated run.py(see [commit](https://github.com/GenomicsDB/GenomicsDB/pull/276/commits/5359c3515690032257ce2e74961a7b7b687c0434) to implicitly use python3. So, if you do a `git pull origin ng_build_ubuntu_22.04` from your repository, you should be able to run `make test` without resorting to running run.py manually.

**Review by mlathara — APPROVED** [review]
lgtm

**Review by eneskuluk — DISMISSED** [review]
looks good to me as well

**Pull request merged**
